// Automatically generated by running `npm run build:snippets`

export type SnippetId =
  | 'import-dynamic-js'
  | 'import-dynamic-ts'
  | 'import-static'
  | 'studio-config'
  | 'cli-config'
  | 'studio-config-create-theme'
  | 'import-create-theme-static'
  | 'import-create-theme-dynamic'
  | 'themer.d.ts'

export function snippet(id: SnippetId) {
  switch (id) {
    case 'import-dynamic-js':
      return (first: string) => `const { theme } = await import(${first})`

    case 'import-dynamic-ts':
      return (first: string) => `const { theme } = (await import(
  // @ts-expect-error -- TODO setup themer.d.ts to get correct typings
  ${first}
)) as { theme: import('sanity').StudioTheme }`

    case 'import-static':
      return (first: string) => `// Add this URL ESM import
import { theme } from ${first}`

    case 'studio-config':
      return (first: string) => `import { createConfig } from 'sanity'
import { deskTool } from 'sanity/desk'

import { schemaTypes } from './schemas'

// 1. Add the import
${first}

export default createConfig({
  theme, // <-- 2. add the theme here

  name: 'default',
  title: 'My Sanity Project',
  projectId: 'b5vzhxkv',
  dataset: 'production',
  plugins: [deskTool()],
  schema: { types: schemaTypes }
})`

    case 'cli-config':
      return () => `import { createCliConfig } from 'sanity/cli'
import type { UserConfig } from 'vite'

export default createCliConfig({
  api: { projectId: 'b5vzhxkv', dataset: 'production' },
  // Change minify and target to allow top-level await in sanity.config.ts
  vite: (config): UserConfig => ({
    ...config,
    build: { ...config.build, minify: 'esbuild', target: 'esnext' }
  })
})`

    case 'studio-config-create-theme':
      return (first: string) => `import { createConfig } from 'sanity'
import { deskTool } from 'sanity/desk'

import { schemaTypes } from './schemas'

${first}

export default createConfig({
  theme: createTheme({
    // override just the bits you want to iterate on
    ...hues,
    primary: { ...hues.primary, mid: '#22fca8' }
  }),

  name: 'default',
  title: 'My Sanity Project',
  projectId: 'b5vzhxkv',
  dataset: 'production',
  plugins: [deskTool()],
  schema: { types: schemaTypes }
})`

    case 'import-create-theme-static':
      return (
        first: string
      ) => `// Use createTheme and hues to iterate locally without needing to mess with URLs
import { createTheme, hues } from ${first}`

    case 'import-create-theme-dynamic':
      return (
        first: string
      ) => `// Use createTheme and hues to iterate locally without needing to mess with URLs
const { createTheme, hues } = await import(
  ${first}
)`

    case 'themer.d.ts':
      return (first: string) => `module ${first} {
  interface Hue
    extends Omit<import('@sanity/color').ColorHueConfig, 'title' | 'midPoint'> {
    midPoint: 50 | 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | 950
  }
  interface Hues {
    default: Hue
    transparent: Hue
    primary: Hue
    positive: Hue
    caution: Hue
    critical: Hue
  }
  const hues: Hues
  type Theme = import('sanity').StudioTheme
  const createTheme = (hues: Hues): Theme => theme
  const theme: Theme

  export { hues, createTheme, theme }
}`

    default:
      throw new TypeError('Unknown snippet id: ' + id)
  }
}
