// @ts-check
// Compiles snippets so they have prettier formatting pre-applied

import parserTypescript from 'prettier/esm/parser-typescript.mjs'
import prettier from 'prettier/esm/standalone.mjs'
import writeFileAtomic from 'write-file-atomic'

const keys = ['__FIRST__', '__SECOND__'].map((_) => JSON.stringify(_))
const args = ['first', 'second']
const dummies = {
  esmUrl: JSON.stringify('https://example.com/api/hues'),
  themeImport: 'theme',
  themeConfigProperty: 'theme,',
  import: "import {studioTheme as theme} from '@sanity/ui'",
}

const sanityConfigCode = (
  themeImport,
  themeConfig = 'theme,'
) => `// sanity.config.ts
import { createConfig } from 'sanity'
import { deskTool } from 'sanity/desk'

import { schemaTypes } from './schemas'

${themeImport}

export default createConfig({
  ${themeConfig}

  name: 'default',
  title: 'My Sanity Project',
  projectId: 'b5vzhxkv',
  dataset: 'production',
  plugins: [deskTool()],
  schema: { types: schemaTypes,},
})

`

const snippets = [
  [
    'import-dynamic-js',
    ['esmUrl'],
    `
const {theme} = await import(${dummies.esmUrl})
`,
  ],
  [
    'import-dynamic-ts',
    ['esmUrl'],
    `
    const { theme } = (await import(
      // @ts-expect-error -- TODO setup themer.d.ts to get correct typings
      ${dummies.esmUrl}
    )) as { theme: import('sanity').StudioTheme }
`,
  ],
  [
    'import-static',
    ['esmUrl'],
    `
  // Add this URL ESM import
  import { theme } from ${dummies.esmUrl};
`,
  ],
  [
    'studio-config',
    ['import', 'themeConfigProperty'],
    `// sanity.config.ts
import { createConfig } from 'sanity'
import { deskTool } from 'sanity/desk'

import { schemaTypes } from './schemas'

${dummies.import}

export default createConfig({
  ${dummies.themeConfigProperty}


  name: 'default',
  title: 'My Sanity Project',
  projectId: 'b5vzhxkv',
  dataset: 'production',
  plugins: [deskTool()],
  schema: { types: schemaTypes,},
})

`,
  ],
]

// Sanity check
const idsChecked = new Set()
for (const [id] of snippets) {
  if (idsChecked.has(id)) {
    throw new Error(`Duplicate id: ${id}`)
  }
  idsChecked.add(id)
}

const ids = snippets.map(([id]) => id)
const idsType = ids.map((id) => JSON.stringify(id)).join(' | ')
const getArgs = (argsLength) => {
  const input = args.map((_) => `${_}: string`)
  switch (argsLength) {
    case 1:
      return input[0]
    case 2:
      return [input[0], input[1]].join(', ')
    default:
      return ''
  }
}

console.group('snippets.map')
const cases = snippets.map(([id, argsLength, snippet]) => {
  console.group('prettier')
  let code = prettier.format(snippet, {
    parser: 'typescript',
    plugins: [parserTypescript],
    semi: false,
    trailingComma: 'none',
  })
  console.log(code)
  console.groupEnd()
  for (const i in keys) {
    const key = keys[i]
    const arg = `\${${args[i]}}`
    code = code.replace(key, arg)
  }
  return `
  case ${JSON.stringify(id)}:
    return (${getArgs(argsLength)}) => \`${code}\`
  `
})
console.groupCollapsed()

const codeSnippets = `
// Automatically generated by running \`npm run build:snippets\`

export type SnippetId = ${idsType};

export function snippet(id: SnippetId) {
  switch (id) {
    ${cases.join('\n')}
    default:
      throw new TypeError('Unknown snippet id: ' + id);
  }
}
`

const dest = new URL('../utils/snippets.ts', import.meta.url)
await writeFileAtomic(dest.pathname, codeSnippets)
